
on:
  push:
    branches: [main, master]
    paths-ignore: '**/README.md'
  pull_request:
    branches: [main, master]
    paths-ignore: '**/README.md'

name: deploy-shiny

jobs:
  deploy-shiny:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup system dependencies
        run: |
          packages=(
            libcurl4-openssl-dev
            libgdal-dev
            libproj-dev
            libudunits2-dev
          )
          sudo apt-get update
          sudo apt-get install --yes "${packages[@]}"

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: renv

      - name: Setup R dependencies
        uses: r-lib/actions/setup-renv@v2

      - name: Lint R
        if: always()
        shell: Rscript {0}
        run: rhino::lint_r()

     - name: Run R unit tests
        if: always()
        shell: Rscript {0}
        run: rhino::test_r()
   
      - name: Push to shinyapps.io
        run: |
          rsconnect::setAccountInfo(name="${{secrets.SHINY_ACC_NAME}}", token="${{secrets.TOKEN}}", secret="${{secrets.SECRET}}")
          rsconnect::deployApp(appName = 'WSBEvolutionCalc')
        shell: Rscript {0}
